name: Squad APK Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y buildozer python3-pip
        pip install --upgrade pip
        pip install kivy speechrecognition

    - name: Build APK
      run: |
        buildozer android debug
        mkdir -p release
        cp bin/*.apk release/squad-v3.apk

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: squad-v3.apk
        path: release/squad-v3.apk
